#ifndef UTILITY_H
#define UTILITY_H

#include <stdint.h>
#include <stdbool.h>
#include "bytes.h"
#if CONFIG_OS_EN
#include "os_wrapper.h"
#endif

/**
 * @brief Lock interrupts.
 *
 * This routine disables all interrupts on the CPU. It returns an unsigned
 * integer "lock-out key", which is an indicator of whether interrupts were
 * locked prior to the call. The lock-out key must be passed to irq_unlock()
 * to re-enable interrupts.
 *
 * @warning
 * The lock-out key should never be used to manually re-enable interrupts
 * or to inspect or manipulate the contents of the CPU's interrupt bits.
 *
 * @return A lock-out key representing the
 *         "interrupt disable state" prior to the call.
 */
uint32_t irq_lock(void);

/**
 * @brief Unlock interrupts.
 *
 * This routine reverses the effect of a previous call to irq_lock() using
 * the associated lock-out key. The caller must call the routine once for
 * each time it called irq_lock(), supplying the keys in the reverse order
 * they were acquired, before interrupts are enabled.
 *
 * @note Can be called by ISRs.
 *
 * @param key Lock-out key generated by irq_lock().
 *
 * @return N/A
 */
void irq_unlock(uint32_t key);

/**
 * @brief : Verify that the current program is in interrupt.
 */
bool IN_ISR(void);

/*******************************************************************************
 * Critical Region API
 ******************************************************************************/
uint32_t critical_region_enter(void);
void critical_region_exit(uint32_t state);

#define CRITICAL_REGION_ENTER(state)   state = critical_region_enter()
#define CRITICAL_REGION_EXIT(state)    critical_region_exit(state)


/*******************************************************************************
 * MAC Address API
 ******************************************************************************/
uint8_t pan10x_mac_addr_get(uint8_t *mac);
uint8_t pan10x_roll_mac_addr_get(uint8_t *mac);

char *addr_to_str(const void *addr);

#endif // UTILITY_H
