/**
 *******************************************************************************
 * @file     utility.c
 * @create   2024-11-01
 * @author   Panchip BLE GROUP
 * @note
 * Copyright (c) 2022-2025 Shanghai Panchip Microelectronics Co.,Ltd.
 *
 *******************************************************************************
 */
#include "utility.h"
#include "FreeRTOS.h"
#include "task.h"
#include "cmsis_compiler.h"
#include "simple_print.h"

/*******************************************************************************
 * OS Hook
 ******************************************************************************/
#if configCHECK_FOR_STACK_OVERFLOW
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    SIMPLE_PRINTS("[E] ", __FUNCTION__, "(): ");
    SIMPLE_PRINTS("Task stack overflow detected: ", pcTaskName, "()\n");
    SYS_ABORT();
}
#endif

#if configUSE_MALLOC_FAILED_HOOK
void vApplicationMallocFailedHook(void)
{
    SIMPLE_PRINTS("[W] ", __FUNCTION__, "(): ");
    SIMPLE_PRINTS(NULL, "OS Heap Size is not enough!\n", NULL);
}
#endif

/**
 * @brief Lock interrupts.
 *
 * This routine disables all interrupts on the CPU. It returns an unsigned
 * integer "lock-out key", which is an indicator of whether interrupts were
 * locked prior to the call. The lock-out key must be passed to irq_unlock()
 * to re-enable interrupts.
 *
 * @warning
 * The lock-out key should never be used to manually re-enable interrupts
 * or to inspect or manipulate the contents of the CPU's interrupt bits.
 *
 * @return A lock-out key representing the
 *         "interrupt disable state" prior to the call.
 */
__ASM uint32_t irq_lock(void)
{
    mrs r0, PRIMASK
    cpsid i
    bx lr
}

/**
 * @brief Unlock interrupts.
 *
 * This routine reverses the effect of a previous call to irq_lock() using
 * the associated lock-out key. The caller must call the routine once for
 * each time it called irq_lock(), supplying the keys in the reverse order
 * they were acquired, before interrupts are enabled.
 *
 * @note Can be called by ISRs.
 *
 * @param key Lock-out key generated by irq_lock().
 *
 * @return N/A
 */
__ASM void irq_unlock(uint32_t key)
{
    msr PRIMASK, r0
    bx lr
}

/**
 * @brief : Verify that the current program is in interrupt.
 */
bool IN_ISR(void)
{
    return (SCB->ICSR & SCB_ICSR_VECTACTIVE_Msk) != 0;
}
