/**
 * This file was generated by Apache newt version: 1.10.0-dev
 */

#ifndef H_MYNEWT_LOGCFG_
#define H_MYNEWT_LOGCFG_

#include "modlog/modlog.h"
#include "log_common/log_common.h"
#include "pan_sys_log.h"

#define BLE_HS_LOG_DEBUG(fmt, ...)      __SYS_LOG(PAN_SYS_LOG_LVL_DBG, fmt "\n", ##__VA_ARGS__)
#define BLE_HS_LOG_INFO(fmt, ...)       __SYS_LOG(PAN_SYS_LOG_LVL_INF, fmt "\n", ##__VA_ARGS__)
#define BLE_HS_LOG_WARN(fmt, ...)       __SYS_LOG(PAN_SYS_LOG_LVL_WRN, fmt "\n", ##__VA_ARGS__)
#define BLE_HS_LOG_ERROR(fmt, ...)      __SYS_LOG(PAN_SYS_LOG_LVL_ERR, fmt "\n", ##__VA_ARGS__)

//#define BLE_HS_LOG_DEBUG(...) IGNORE(__VA_ARGS__)
//#define BLE_HS_LOG_INFO(...) MODLOG_INFO(4, __VA_ARGS__)
//#define BLE_HS_LOG_WARN(...) MODLOG_WARN(4, __VA_ARGS__)
//#define BLE_HS_LOG_ERROR(...) MODLOG_ERROR(4, __VA_ARGS__)
//#define BLE_HS_LOG_CRITICAL(...) MODLOG_CRITICAL(4, __VA_ARGS__)
//#define BLE_HS_LOG_DISABLED(...) MODLOG_DISABLED(4, __VA_ARGS__)

//#define DFLT_LOG_DEBUG(...) IGNORE(__VA_ARGS__)
//#define DFLT_LOG_INFO(...) MODLOG_INFO(0, __VA_ARGS__)
//#define DFLT_LOG_WARN(...) MODLOG_WARN(0, __VA_ARGS__)
//#define DFLT_LOG_ERROR(...) MODLOG_ERROR(0, __VA_ARGS__)
//#define DFLT_LOG_CRITICAL(...) MODLOG_CRITICAL(0, __VA_ARGS__)
//#define DFLT_LOG_DISABLED(...) MODLOG_DISABLED(0, __VA_ARGS__)

#endif
